/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pabe' at '16/10/15 15:41' with Gradle 2.7
 *
 * @author pabe, @date 16/10/15 15:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
